DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'archive') THEN
        CREATE SCHEMA archive;
    END IF;
END $EF$;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'appointment') THEN
        CREATE SCHEMA appointment;
    END IF;
END $EF$;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'catalog') THEN
        CREATE SCHEMA catalog;
    END IF;
END $EF$;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'system') THEN
        CREATE SCHEMA system;
    END IF;
END $EF$;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'geographic') THEN
        CREATE SCHEMA geographic;
    END IF;
END $EF$;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'insurance') THEN
        CREATE SCHEMA insurance;
    END IF;
END $EF$;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'facility') THEN
        CREATE SCHEMA facility;
    END IF;
END $EF$;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'billing') THEN
        CREATE SCHEMA billing;
    END IF;
END $EF$;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'organization') THEN
        CREATE SCHEMA organization;
    END IF;
END $EF$;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'patient') THEN
        CREATE SCHEMA patient;
    END IF;
END $EF$;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'practitioner') THEN
        CREATE SCHEMA practitioner;
    END IF;
END $EF$;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'scheduling') THEN
        CREATE SCHEMA scheduling;
    END IF;
END $EF$;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'pricing') THEN
        CREATE SCHEMA pricing;
    END IF;
END $EF$;


CREATE TABLE archive.appointment_archives (
    appointment_id uuid NOT NULL,
    archived_at timestamp with time zone NOT NULL,
    archived_by_user_id uuid,
    original_data jsonb NOT NULL,
    CONSTRAINT pk_appointment_archives PRIMARY KEY (appointment_id)
);


CREATE TABLE appointment.appointment_clinical_details (
    clinical_detail_id uuid NOT NULL,
    appointment_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    patient_notes text,
    internal_notes text,
    created_at timestamp with time zone NOT NULL,
    created_by uuid,
    updated_at timestamp with time zone,
    updated_by uuid,
    deleted_at timestamp with time zone,
    deleted_by uuid,
    CONSTRAINT pk_appointment_clinical_details PRIMARY KEY (clinical_detail_id)
);


CREATE TABLE appointment.appointment_histories (
    history_id integer GENERATED BY DEFAULT AS IDENTITY,
    appointment_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    changed_at timestamp with time zone NOT NULL,
    changed_by_user_id uuid,
    change_type text NOT NULL,
    old_value jsonb,
    new_value jsonb,
    notes text,
    CONSTRAINT pk_appointment_histories PRIMARY KEY (history_id)
);


CREATE TABLE catalog.appointment_statuses (
    status_code text NOT NULL,
    name text NOT NULL,
    description text,
    is_final boolean NOT NULL,
    allowed_transitions text,
    CONSTRAINT pk_appointment_statuses PRIMARY KEY (status_code)
);


CREATE TABLE appointment.appointments (
    appointment_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    appointment_number text NOT NULL,
    patient_id uuid NOT NULL,
    practitioner_id uuid NOT NULL,
    location_id integer NOT NULL,
    specialty_id integer NOT NULL,
    service_id integer NOT NULL,
    slot_id integer NOT NULL,
    appointment_date text NOT NULL,
    start_at timestamp with time zone NOT NULL,
    end_at timestamp with time zone NOT NULL,
    status_code text NOT NULL,
    is_telehealth boolean NOT NULL,
    patient_insurance_id integer,
    requires_pre_auth boolean NOT NULL,
    pre_auth_code text,
    booked_by_user_id uuid,
    booking_channel text,
    arrived_at timestamp with time zone,
    seen_at timestamp with time zone,
    completed_at timestamp with time zone,
    cancelled_at timestamp with time zone,
    cancellation_reason_id integer,
    cancellation_notes text,
    version integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by uuid,
    updated_at timestamp with time zone,
    updated_by uuid,
    deleted_at timestamp with time zone,
    deleted_by uuid,
    CONSTRAINT pk_appointments PRIMARY KEY (appointment_id)
);


CREATE TABLE system.audit_logs (
    audit_log_id uuid NOT NULL,
    table_name text NOT NULL,
    record_id text NOT NULL,
    operation text NOT NULL,
    user_id uuid,
    operated_at timestamp with time zone NOT NULL,
    old_values jsonb,
    new_values jsonb,
    ip_address text,
    user_agent text,
    CONSTRAINT pk_audit_logs PRIMARY KEY (audit_log_id)
);


CREATE TABLE catalog.cancellation_reasons (
    reason_id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    name text NOT NULL,
    applies_to_status text,
    requires_refund boolean NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT pk_cancellation_reasons PRIMARY KEY (reason_id)
);


CREATE TABLE geographic.cities (
    city_id integer GENERATED BY DEFAULT AS IDENTITY,
    state_id integer NOT NULL,
    code text,
    name text NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT pk_cities PRIMARY KEY (city_id)
);


CREATE TABLE system.configurations (
    config_key text NOT NULL,
    config_value text NOT NULL,
    data_type text NOT NULL,
    description text,
    created_at timestamp with time zone NOT NULL,
    created_by uuid,
    updated_at timestamp with time zone,
    updated_by uuid,
    deleted_at timestamp with time zone,
    deleted_by uuid,
    CONSTRAINT pk_configurations PRIMARY KEY (config_key)
);


CREATE TABLE catalog.contact_types (
    contact_type_id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    name text NOT NULL,
    validation_regex text,
    is_active boolean NOT NULL,
    CONSTRAINT pk_contact_types PRIMARY KEY (contact_type_id)
);


CREATE TABLE geographic.countries (
    country_id integer GENERATED ALWAYS AS IDENTITY,
    country_code character varying(2) NOT NULL,
    iso3code text NOT NULL,
    name text NOT NULL,
    phone_code text,
    is_active boolean NOT NULL,
    CONSTRAINT pk_countries PRIMARY KEY (country_id)
);


CREATE TABLE insurance.coverage_types (
    type_id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    name text NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT pk_coverage_types PRIMARY KEY (type_id)
);


CREATE TABLE catalog.currencies (
    currency_code text NOT NULL,
    name text NOT NULL,
    symbol text,
    decimal_places smallint NOT NULL,
    CONSTRAINT pk_currencies PRIMARY KEY (currency_code)
);


CREATE TABLE catalog.document_types (
    type_id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    name text NOT NULL,
    country_id integer,
    validation_regex text,
    is_active boolean NOT NULL,
    CONSTRAINT pk_document_types PRIMARY KEY (type_id)
);


CREATE TABLE facility.equipments (
    equipment_id integer GENERATED BY DEFAULT AS IDENTITY,
    location_id integer NOT NULL,
    room_id integer,
    tenant_id uuid NOT NULL,
    name text NOT NULL,
    serial_number text,
    requires_maintenance boolean NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_equipments PRIMARY KEY (equipment_id)
);


CREATE TABLE billing.invoice_line_items (
    line_item_id integer GENERATED BY DEFAULT AS IDENTITY,
    invoice_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    service_id integer NOT NULL,
    description text NOT NULL,
    quantity numeric NOT NULL,
    unit_price numeric NOT NULL,
    subtotal numeric NOT NULL,
    tax numeric NOT NULL,
    total numeric NOT NULL,
    CONSTRAINT pk_invoice_line_items PRIMARY KEY (line_item_id)
);


CREATE TABLE billing.invoices (
    invoice_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    invoice_number text NOT NULL,
    appointment_id uuid NOT NULL,
    patient_id uuid NOT NULL,
    issue_date text NOT NULL,
    due_date text,
    subtotal numeric NOT NULL,
    tax numeric NOT NULL,
    discount numeric NOT NULL,
    total numeric NOT NULL,
    currency_code text NOT NULL,
    status_code text NOT NULL,
    notes text,
    created_at timestamp with time zone NOT NULL,
    created_by uuid,
    updated_at timestamp with time zone,
    updated_by uuid,
    deleted_at timestamp with time zone,
    deleted_by uuid,
    CONSTRAINT pk_invoices PRIMARY KEY (invoice_id)
);


CREATE TABLE organization.location_addresses (
    address_id integer GENERATED BY DEFAULT AS IDENTITY,
    location_id integer NOT NULL,
    tenant_id uuid NOT NULL,
    city_id integer NOT NULL,
    address_line1 text NOT NULL,
    address_line2 text,
    neighborhood text,
    postal_code text,
    reference text,
    latitude numeric NOT NULL,
    longitude numeric NOT NULL,
    is_primary boolean NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT pk_location_addresses PRIMARY KEY (address_id)
);


CREATE TABLE organization.location_contacts (
    contact_id integer GENERATED BY DEFAULT AS IDENTITY,
    location_id integer NOT NULL,
    tenant_id uuid NOT NULL,
    contact_type_id integer NOT NULL,
    contact_value text NOT NULL,
    purpose text,
    is_primary boolean NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT pk_location_contacts PRIMARY KEY (contact_id)
);


CREATE TABLE organization.location_specialties (
    location_specialty_id integer GENERATED BY DEFAULT AS IDENTITY,
    location_id integer NOT NULL,
    specialty_id integer NOT NULL,
    tenant_id uuid NOT NULL,
    is_active boolean NOT NULL,
    activated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_location_specialties PRIMARY KEY (location_specialty_id)
);


CREATE TABLE organization.locations (
    location_id integer GENERATED BY DEFAULT AS IDENTITY,
    organization_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    name text NOT NULL,
    code text,
    is_head_office boolean NOT NULL,
    timezone text NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by uuid,
    updated_at timestamp with time zone,
    updated_by uuid,
    deleted_at timestamp with time zone,
    deleted_by uuid,
    CONSTRAINT pk_locations PRIMARY KEY (location_id)
);


CREATE TABLE organization.organization_types (
    type_id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    name text NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT pk_organization_types PRIMARY KEY (type_id)
);


CREATE TABLE organization.organizations (
    organization_id uuid NOT NULL,
    legal_name text NOT NULL,
    trade_name text,
    tax_id text,
    document_type_id integer,
    organization_type_id integer NOT NULL,
    country_id integer NOT NULL,
    website text,
    logo_url text,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by uuid,
    updated_at timestamp with time zone,
    updated_by uuid,
    deleted_at timestamp with time zone,
    deleted_by uuid,
    CONSTRAINT pk_organizations PRIMARY KEY (organization_id)
);


CREATE TABLE patient.patient_addresses (
    address_id integer GENERATED BY DEFAULT AS IDENTITY,
    patient_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    city_id integer NOT NULL,
    address_line1 text NOT NULL,
    address_line2 text,
    postal_code text,
    is_primary boolean NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT pk_patient_addresses PRIMARY KEY (address_id)
);


CREATE TABLE patient.patient_consents (
    consent_id uuid NOT NULL,
    patient_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    appointment_id uuid,
    consent_type text NOT NULL,
    document_url text,
    agreed_at timestamp with time zone NOT NULL,
    ip_address text,
    is_active boolean NOT NULL,
    CONSTRAINT pk_patient_consents PRIMARY KEY (consent_id)
);


CREATE TABLE patient.patient_contacts (
    patient_contact_id integer GENERATED BY DEFAULT AS IDENTITY,
    patient_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    contact_type_id integer NOT NULL,
    contact_value text NOT NULL,
    purpose text,
    is_primary boolean NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT pk_patient_contacts PRIMARY KEY (patient_contact_id)
);


CREATE TABLE patient.patient_insurances (
    patient_insurance_id integer GENERATED BY DEFAULT AS IDENTITY,
    patient_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    payer_id integer NOT NULL,
    plan_id integer,
    member_number text,
    policy_number text,
    valid_from text NOT NULL,
    valid_to text,
    is_primary boolean NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by uuid,
    updated_at timestamp with time zone,
    updated_by uuid,
    deleted_at timestamp with time zone,
    deleted_by uuid,
    CONSTRAINT pk_patient_insurances PRIMARY KEY (patient_insurance_id)
);


CREATE TABLE patient.patient_relations (
    relation_id uuid NOT NULL,
    primary_patient_id uuid NOT NULL,
    dependent_patient_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    relationship_type text NOT NULL,
    can_book_appointments boolean NOT NULL,
    can_access_medical_records boolean NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_patient_relations PRIMARY KEY (relation_id)
);


CREATE TABLE patient.patients (
    patient_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    document_type_id integer NOT NULL,
    document_number text NOT NULL,
    first_name text NOT NULL,
    middle_name text,
    last_name text NOT NULL,
    second_last_name text,
    birth_date text,
    gender text,
    user_id uuid,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by uuid,
    updated_at timestamp with time zone,
    updated_by uuid,
    deleted_at timestamp with time zone,
    deleted_by uuid,
    CONSTRAINT pk_patients PRIMARY KEY (patient_id)
);


CREATE TABLE insurance.payer_provider_networks (
    network_id integer GENERATED BY DEFAULT AS IDENTITY,
    payer_id integer NOT NULL,
    organization_id uuid NOT NULL,
    contract_code text,
    valid_from text NOT NULL,
    valid_to text,
    is_active boolean NOT NULL,
    CONSTRAINT pk_payer_provider_networks PRIMARY KEY (network_id)
);


CREATE TABLE insurance.payers (
    payer_id integer GENERATED BY DEFAULT AS IDENTITY,
    coverage_type_id integer NOT NULL,
    country_id integer NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    tax_id text,
    is_active boolean NOT NULL,
    CONSTRAINT pk_payers PRIMARY KEY (payer_id)
);


CREATE TABLE catalog.payment_methods (
    method_id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    name text NOT NULL,
    requires_gateway boolean NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT pk_payment_methods PRIMARY KEY (method_id)
);


CREATE TABLE catalog.payment_statuses (
    status_code text NOT NULL,
    name text NOT NULL,
    is_final boolean NOT NULL,
    CONSTRAINT pk_payment_statuses PRIMARY KEY (status_code)
);


CREATE TABLE billing.payments (
    payment_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    payment_number text NOT NULL,
    invoice_id uuid NOT NULL,
    amount numeric NOT NULL,
    currency_code text NOT NULL,
    payment_method_id integer NOT NULL,
    status_code text NOT NULL,
    transaction_reference text,
    processed_at timestamp with time zone,
    patient_insurance_id integer,
    notes text,
    created_at timestamp with time zone NOT NULL,
    created_by uuid,
    CONSTRAINT pk_payments PRIMARY KEY (payment_id)
);


CREATE TABLE insurance.plans (
    plan_id integer GENERATED BY DEFAULT AS IDENTITY,
    payer_id integer NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    description text,
    coverage_percentage numeric,
    requires_pre_auth boolean NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT pk_plans PRIMARY KEY (plan_id)
);


CREATE TABLE practitioner.practitioner_contacts (
    practitioner_contact_id integer GENERATED BY DEFAULT AS IDENTITY,
    practitioner_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    contact_type_id integer NOT NULL,
    contact_value text NOT NULL,
    purpose text,
    is_primary boolean NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT pk_practitioner_contacts PRIMARY KEY (practitioner_contact_id)
);


CREATE TABLE practitioner.practitioner_locations (
    practitioner_location_id integer GENERATED BY DEFAULT AS IDENTITY,
    practitioner_id uuid NOT NULL,
    location_id integer NOT NULL,
    tenant_id uuid NOT NULL,
    is_primary boolean NOT NULL,
    start_date text NOT NULL,
    end_date text,
    is_active boolean NOT NULL,
    CONSTRAINT pk_practitioner_locations PRIMARY KEY (practitioner_location_id)
);


CREATE TABLE scheduling.practitioner_schedules (
    schedule_id integer GENERATED BY DEFAULT AS IDENTITY,
    tenant_id uuid NOT NULL,
    practitioner_id uuid NOT NULL,
    location_specialty_id integer NOT NULL,
    room_id integer,
    weekday_id smallint NOT NULL,
    start_time text NOT NULL,
    end_time text NOT NULL,
    slot_duration_minutes smallint NOT NULL,
    max_patients_per_slot smallint NOT NULL,
    valid_from text NOT NULL,
    valid_to text,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by uuid,
    updated_at timestamp with time zone,
    updated_by uuid,
    deleted_at timestamp with time zone,
    deleted_by uuid,
    CONSTRAINT pk_practitioner_schedules PRIMARY KEY (schedule_id)
);


CREATE TABLE practitioner.practitioner_specialties (
    practitioner_specialty_id integer GENERATED BY DEFAULT AS IDENTITY,
    practitioner_id uuid NOT NULL,
    specialty_id integer NOT NULL,
    tenant_id uuid NOT NULL,
    is_primary boolean NOT NULL,
    certification_date text,
    is_active boolean NOT NULL,
    CONSTRAINT pk_practitioner_specialties PRIMARY KEY (practitioner_specialty_id)
);


CREATE TABLE practitioner.practitioners (
    practitioner_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    document_type_id integer NOT NULL,
    document_number text NOT NULL,
    first_name text NOT NULL,
    last_name text NOT NULL,
    medical_license text,
    user_id uuid,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by uuid,
    updated_at timestamp with time zone,
    updated_by uuid,
    deleted_at timestamp with time zone,
    deleted_by uuid,
    CONSTRAINT pk_practitioners PRIMARY KEY (practitioner_id)
);


CREATE TABLE pricing.price_lists (
    price_list_id integer GENERATED BY DEFAULT AS IDENTITY,
    tenant_id uuid NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    description text,
    is_default boolean NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by uuid,
    updated_at timestamp with time zone,
    updated_by uuid,
    deleted_at timestamp with time zone,
    deleted_by uuid,
    CONSTRAINT pk_price_lists PRIMARY KEY (price_list_id)
);


CREATE TABLE catalog.refund_statuses (
    status_code text NOT NULL,
    name text NOT NULL,
    description text,
    is_final boolean NOT NULL,
    CONSTRAINT pk_refund_statuses PRIMARY KEY (status_code)
);


CREATE TABLE billing.refunds (
    refund_id integer GENERATED BY DEFAULT AS IDENTITY,
    payment_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    amount numeric NOT NULL,
    currency_code text NOT NULL,
    reason text NOT NULL,
    processed_at timestamp with time zone,
    transaction_reference text,
    status_code text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by uuid,
    CONSTRAINT pk_refunds PRIMARY KEY (refund_id)
);


CREATE TABLE facility.rooms (
    room_id integer GENERATED BY DEFAULT AS IDENTITY,
    location_id integer NOT NULL,
    tenant_id uuid NOT NULL,
    name text NOT NULL,
    room_type text NOT NULL,
    capacity smallint NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by uuid,
    updated_at timestamp with time zone,
    updated_by uuid,
    deleted_at timestamp with time zone,
    deleted_by uuid,
    CONSTRAINT pk_rooms PRIMARY KEY (room_id)
);


CREATE TABLE scheduling.schedule_exceptions (
    exception_id integer GENERATED BY DEFAULT AS IDENTITY,
    tenant_id uuid NOT NULL,
    schedule_id integer,
    practitioner_id uuid NOT NULL,
    location_specialty_id integer,
    exception_date text NOT NULL,
    is_closed boolean NOT NULL,
    override_start_time text,
    override_end_time text,
    reason text,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_schedule_exceptions PRIMARY KEY (exception_id)
);


CREATE TABLE pricing.service_prices (
    service_price_id integer GENERATED BY DEFAULT AS IDENTITY,
    tenant_id uuid NOT NULL,
    price_list_id integer NOT NULL,
    location_id integer,
    specialty_id integer,
    service_id integer NOT NULL,
    practitioner_id uuid,
    price numeric NOT NULL,
    currency_code text NOT NULL,
    valid_from text NOT NULL,
    valid_to text,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by uuid,
    updated_at timestamp with time zone,
    updated_by uuid,
    deleted_at timestamp with time zone,
    deleted_by uuid,
    CONSTRAINT pk_service_prices PRIMARY KEY (service_price_id)
);


CREATE TABLE catalog.services (
    service_id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    name text NOT NULL,
    description text,
    default_duration_minutes smallint,
    requires_pre_auth boolean NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT pk_services PRIMARY KEY (service_id)
);


CREATE TABLE scheduling.slots (
    slot_id integer GENERATED BY DEFAULT AS IDENTITY,
    tenant_id uuid NOT NULL,
    practitioner_id uuid NOT NULL,
    location_specialty_id integer NOT NULL,
    room_id integer,
    slot_start_at timestamp with time zone NOT NULL,
    slot_end_at timestamp with time zone NOT NULL,
    max_capacity smallint NOT NULL,
    reservation_status text NOT NULL,
    held_until timestamp with time zone,
    version integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_slots PRIMARY KEY (slot_id)
);


CREATE TABLE catalog.specialty_categories (
    category_id integer GENERATED ALWAYS AS IDENTITY,
    code character varying(50) NOT NULL,
    name_es character varying(150) NOT NULL,
    name_en character varying(150) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by uuid,
    updated_at timestamp with time zone,
    updated_by uuid,
    deleted_at timestamp with time zone,
    deleted_by uuid,
    CONSTRAINT pk_specialty_categories PRIMARY KEY (category_id)
);


CREATE TABLE geographic.states (
    state_id integer GENERATED BY DEFAULT AS IDENTITY,
    country_id integer NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT pk_states PRIMARY KEY (state_id)
);


CREATE TABLE appointment.telehealth_sessions (
    session_id uuid NOT NULL,
    appointment_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    meeting_url text NOT NULL,
    host_token text,
    guest_token text,
    status text NOT NULL,
    started_at timestamp with time zone,
    ended_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    created_by uuid,
    updated_at timestamp with time zone,
    updated_by uuid,
    deleted_at timestamp with time zone,
    deleted_by uuid,
    CONSTRAINT pk_telehealth_sessions PRIMARY KEY (session_id)
);


CREATE TABLE system.users (
    user_id uuid NOT NULL,
    username text NOT NULL,
    email text NOT NULL,
    password_hash text,
    external_provider_id text,
    full_name text NOT NULL,
    user_type text NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by uuid,
    updated_at timestamp with time zone,
    updated_by uuid,
    deleted_at timestamp with time zone,
    deleted_by uuid,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);


CREATE TABLE scheduling.waitlists (
    waitlist_id integer GENERATED BY DEFAULT AS IDENTITY,
    tenant_id uuid NOT NULL,
    patient_id uuid NOT NULL,
    practitioner_id uuid,
    specialty_id integer NOT NULL,
    preferred_date_from text NOT NULL,
    preferred_date_to text NOT NULL,
    status text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by uuid,
    updated_at timestamp with time zone,
    updated_by uuid,
    deleted_at timestamp with time zone,
    deleted_by uuid,
    CONSTRAINT pk_waitlists PRIMARY KEY (waitlist_id)
);


CREATE TABLE scheduling.weekdays (
    weekday_id smallint GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    name text NOT NULL,
    CONSTRAINT pk_weekdays PRIMARY KEY (weekday_id)
);


CREATE TABLE catalog.specialties (
    specialty_id integer GENERATED ALWAYS AS IDENTITY,
    snomed_code character varying(20) NOT NULL,
    name_es character varying(150) NOT NULL,
    name_en character varying(150) NOT NULL,
    category_id integer NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT pk_specialties PRIMARY KEY (specialty_id),
    CONSTRAINT fk_specialties_specialty_categories_category_id FOREIGN KEY (category_id) REFERENCES catalog.specialty_categories (category_id) ON DELETE RESTRICT
);


INSERT INTO geographic.countries (country_id, country_code, is_active, iso3code, name, phone_code)
OVERRIDING SYSTEM VALUE
VALUES (1, 'EC', TRUE, 'ECU', 'Ecuador', '+593');
INSERT INTO geographic.countries (country_id, country_code, is_active, iso3code, name, phone_code)
OVERRIDING SYSTEM VALUE
VALUES (2, 'CO', TRUE, 'COL', 'Colombia', '+57');
INSERT INTO geographic.countries (country_id, country_code, is_active, iso3code, name, phone_code)
OVERRIDING SYSTEM VALUE
VALUES (3, 'PE', TRUE, 'PER', 'Perú', '+51');
INSERT INTO geographic.countries (country_id, country_code, is_active, iso3code, name, phone_code)
OVERRIDING SYSTEM VALUE
VALUES (4, 'MX', TRUE, 'MEX', 'México', '+52');
INSERT INTO geographic.countries (country_id, country_code, is_active, iso3code, name, phone_code)
OVERRIDING SYSTEM VALUE
VALUES (5, 'AR', TRUE, 'ARG', 'Argentina', '+54');
INSERT INTO geographic.countries (country_id, country_code, is_active, iso3code, name, phone_code)
OVERRIDING SYSTEM VALUE
VALUES (6, 'CL', TRUE, 'CHL', 'Chile', '+56');
INSERT INTO geographic.countries (country_id, country_code, is_active, iso3code, name, phone_code)
OVERRIDING SYSTEM VALUE
VALUES (7, 'ES', TRUE, 'ESP', 'España', '+34');
INSERT INTO geographic.countries (country_id, country_code, is_active, iso3code, name, phone_code)
OVERRIDING SYSTEM VALUE
VALUES (8, 'US', TRUE, 'USA', 'Estados Unidos', '+1');
INSERT INTO geographic.countries (country_id, country_code, is_active, iso3code, name, phone_code)
OVERRIDING SYSTEM VALUE
VALUES (9, 'BR', TRUE, 'BRA', 'Brasil', '+55');
INSERT INTO geographic.countries (country_id, country_code, is_active, iso3code, name, phone_code)
OVERRIDING SYSTEM VALUE
VALUES (10, 'UY', TRUE, 'URY', 'Uruguay', '+598');


INSERT INTO catalog.document_types (type_id, code, country_id, is_active, name, validation_regex)
VALUES (1, 'CEDULA', 1, TRUE, 'Cédula de Identidad', NULL);
INSERT INTO catalog.document_types (type_id, code, country_id, is_active, name, validation_regex)
VALUES (2, 'PASAPORTE', NULL, TRUE, 'Pasaporte', NULL);
INSERT INTO catalog.document_types (type_id, code, country_id, is_active, name, validation_regex)
VALUES (3, 'RUC', 1, TRUE, 'Registro Único de Contribuyentes', NULL);
INSERT INTO catalog.document_types (type_id, code, country_id, is_active, name, validation_regex)
VALUES (4, 'NIT', 2, TRUE, 'Número de Identificación Tributaria', NULL);
INSERT INTO catalog.document_types (type_id, code, country_id, is_active, name, validation_regex)
VALUES (5, 'SSN', 8, TRUE, 'Social Security Number', NULL);
INSERT INTO catalog.document_types (type_id, code, country_id, is_active, name, validation_regex)
VALUES (6, 'DNI', 3, TRUE, 'Documento Nacional de Identidad', NULL);
INSERT INTO catalog.document_types (type_id, code, country_id, is_active, name, validation_regex)
VALUES (7, 'RUT', 6, TRUE, 'Rol Único Tributario', NULL);
INSERT INTO catalog.document_types (type_id, code, country_id, is_active, name, validation_regex)
VALUES (8, 'CUIT', 5, TRUE, 'Clave Única de Identificación Tributaria', NULL);
INSERT INTO catalog.document_types (type_id, code, country_id, is_active, name, validation_regex)
VALUES (9, 'CPF', 9, TRUE, 'Cadastro de Pessoas Físicas', NULL);
INSERT INTO catalog.document_types (type_id, code, country_id, is_active, name, validation_regex)
VALUES (10, 'CNPJ', 9, TRUE, 'Cadastro Nacional da Pessoa Jurídica', NULL);


INSERT INTO catalog.specialty_categories (category_id, code, created_at, created_by, deleted_at, deleted_by, is_active, name_en, name_es, updated_at, updated_by)
OVERRIDING SYSTEM VALUE
VALUES (1, 'MEDICINA', TIMESTAMPTZ '-infinity', NULL, NULL, NULL, TRUE, 'Medicine', 'Medicina', NULL, NULL);
INSERT INTO catalog.specialty_categories (category_id, code, created_at, created_by, deleted_at, deleted_by, is_active, name_en, name_es, updated_at, updated_by)
OVERRIDING SYSTEM VALUE
VALUES (2, 'CIRUGIA', TIMESTAMPTZ '-infinity', NULL, NULL, NULL, TRUE, 'Surgery', 'Cirugía', NULL, NULL);
INSERT INTO catalog.specialty_categories (category_id, code, created_at, created_by, deleted_at, deleted_by, is_active, name_en, name_es, updated_at, updated_by)
OVERRIDING SYSTEM VALUE
VALUES (3, 'DIAGNOSTICO', TIMESTAMPTZ '-infinity', NULL, NULL, NULL, TRUE, 'Diagnostics', 'Diagnóstico', NULL, NULL);
INSERT INTO catalog.specialty_categories (category_id, code, created_at, created_by, deleted_at, deleted_by, is_active, name_en, name_es, updated_at, updated_by)
OVERRIDING SYSTEM VALUE
VALUES (4, 'SALUD_MENTAL', TIMESTAMPTZ '-infinity', NULL, NULL, NULL, TRUE, 'Mental Health', 'Salud Mental', NULL, NULL);
INSERT INTO catalog.specialty_categories (category_id, code, created_at, created_by, deleted_at, deleted_by, is_active, name_en, name_es, updated_at, updated_by)
OVERRIDING SYSTEM VALUE
VALUES (5, 'REHABILITACION', TIMESTAMPTZ '-infinity', NULL, NULL, NULL, TRUE, 'Rehabilitation', 'Rehabilitación', NULL, NULL);
INSERT INTO catalog.specialty_categories (category_id, code, created_at, created_by, deleted_at, deleted_by, is_active, name_en, name_es, updated_at, updated_by)
OVERRIDING SYSTEM VALUE
VALUES (6, 'ODONTOLOGIA', TIMESTAMPTZ '-infinity', NULL, NULL, NULL, TRUE, 'Dentistry', 'Odontología', NULL, NULL);
INSERT INTO catalog.specialty_categories (category_id, code, created_at, created_by, deleted_at, deleted_by, is_active, name_en, name_es, updated_at, updated_by)
OVERRIDING SYSTEM VALUE
VALUES (7, 'TERAPIAS', TIMESTAMPTZ '-infinity', NULL, NULL, NULL, TRUE, 'Therapies', 'Terapias', NULL, NULL);
INSERT INTO catalog.specialty_categories (category_id, code, created_at, created_by, deleted_at, deleted_by, is_active, name_en, name_es, updated_at, updated_by)
OVERRIDING SYSTEM VALUE
VALUES (8, 'OTRAS', TIMESTAMPTZ '-infinity', NULL, NULL, NULL, TRUE, 'Other', 'Otras', NULL, NULL);


INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (1, 1, TRUE, 'Cardiology', 'Cardiología', '394579002');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (2, 1, TRUE, 'Pediatrics', 'Pediatría', '394537008');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (3, 1, TRUE, 'Dermatology', 'Dermatología', '394582007');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (4, 2, TRUE, 'Neurology', 'Neurología', '394591006');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (5, 1, TRUE, 'Ophthalmology', 'Oftalmología', '394594003');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (6, 2, TRUE, 'Orthopedic Surgery', 'Cirugía Ortopédica', '394609007');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (7, 1, TRUE, 'Endocrinology', 'Endocrinología', '394586005');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (8, 1, TRUE, 'Gastroenterology', 'Gastroenterología', '394587001');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (9, 1, TRUE, 'Geriatrics', 'Geriatría', '394589003');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (10, 1, TRUE, 'General Practice', 'Medicina General', '394580004');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (11, 1, TRUE, 'Family Medicine', 'Medicina Familiar', '394802001');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (12, 1, TRUE, 'Nephrology', 'Nefrología', '394592004');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (13, 2, TRUE, 'Neurosurgery', 'Neurocirugía', '394593009');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (14, 2, TRUE, 'Obstetrics and Gynecology', 'Obstetricia y Ginecología', '394595002');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (15, 1, TRUE, 'Medical Oncology', 'Oncología Médica', '394597005');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (16, 2, TRUE, 'Otolaryngology', 'Otorrinolaringología', '394598000');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (17, 3, TRUE, 'Pathology', 'Patología', '394600002');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (18, 2, TRUE, 'Pediatric Surgery', 'Cirugía Pediátrica', '394601003');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (19, 2, TRUE, 'Plastic Surgery', 'Cirugía Plástica', '394602005');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (20, 4, TRUE, 'Psychiatry', 'Psiquiatría', '394603000');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (21, 3, TRUE, 'Radiology', 'Radiología', '394604006');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (22, 3, TRUE, 'Radiation Oncology', 'Radioterapia', '394605007');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (23, 5, TRUE, 'Physical Medicine and Rehabilitation', 'Rehabilitación', '394606008');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (24, 1, TRUE, 'Rheumatology', 'Reumatología', '394607004');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (25, 2, TRUE, 'General Surgery', 'Cirugía General', '394608009');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (26, 2, TRUE, 'Urology', 'Urología', '408443003');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (27, 2, TRUE, 'Vascular Surgery', 'Cirugía Vascular', '408444009');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (28, 1, TRUE, 'Emergency Medicine', 'Medicina de Emergencias', '722163007');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (29, 1, TRUE, 'Intensive Care Medicine', 'Medicina Intensiva', '722164001');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (30, 1, TRUE, 'Infectious Diseases', 'Infectología', '722165000');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (31, 1, TRUE, 'Pulmonology', 'Neumología', '722166004');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (32, 1, TRUE, 'Hematology', 'Hematología', '722167008');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (33, 1, TRUE, 'Clinical Immunology', 'Inmunología Clínica', '722168003');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (34, 1, TRUE, 'Internal Medicine', 'Medicina Interna', '722169006');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (35, 1, TRUE, 'Nuclear Medicine', 'Medicina Nuclear', '722170007');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (36, 1, TRUE, 'Pain Medicine', 'Medicina del Dolor', '722171006');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (37, 1, TRUE, 'Anesthesiology', 'Anestesiología', '722172004');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (38, 1, TRUE, 'Allergy', 'Alergología', '722173009');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (39, 1, TRUE, 'Medical Genetics', 'Genética Médica', '722174003');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (40, 1, TRUE, 'Preventive Medicine', 'Medicina Preventiva', '722175002');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (41, 1, TRUE, 'Occupational Medicine', 'Medicina del Trabajo', '722176001');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (42, 1, TRUE, 'Sports Medicine', 'Medicina Deportiva', '722177005');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (43, 1, TRUE, 'Tropical Medicine', 'Medicina Tropical', '722178000');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (44, 1, TRUE, 'Sleep Medicine', 'Medicina del Sueño', '722179008');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (45, 1, TRUE, 'Palliative Medicine', 'Medicina Paliativa', '722180006');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (46, 1, TRUE, 'Hyperbaric Medicine', 'Medicina Hiperbárica', '722181005');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (47, 1, TRUE, 'Aerospace Medicine', 'Medicina Aeroespacial', '722182003');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (48, 1, TRUE, 'Toxicology', 'Toxicología', '722183008');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (49, 3, TRUE, 'Cytopathology', 'Citopatología', '722184002');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (50, 3, TRUE, 'Dermatopathology', 'Dermatopatología', '722185001');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (51, 3, TRUE, 'Neuropathology', 'Neuropatología', '722186000');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (52, 3, TRUE, 'Forensic Pathology', 'Patología Forense', '722187009');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (53, 2, TRUE, 'Cardiovascular Surgery', 'Cirugía Cardiovascular', '722188004');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (54, 2, TRUE, 'Thoracic Surgery', 'Cirugía Torácica', '722189007');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (55, 2, TRUE, 'Oral and Maxillofacial Surgery', 'Cirugía Maxilofacial', '722190003');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (56, 2, TRUE, 'Hand Surgery', 'Cirugía de Mano', '722191004');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (57, 1, TRUE, 'Colorectal Surgery', 'Coloproctología', '722192006');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (58, 2, TRUE, 'Transplant Surgery', 'Trasplantes', '722193001');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (59, 1, TRUE, 'Angiology', 'Angiología', '722194007');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (60, 3, TRUE, 'Cardiac Electrophysiology', 'Electrofisiología Cardíaca', '722195008');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (61, 3, TRUE, 'Interventional Cardiology', 'Hemodinamia', '722196009');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (62, 1, TRUE, 'Maternal Fetal Medicine', 'Medicina Materno Fetal', '722197000');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (63, 1, TRUE, 'Neonatology', 'Neonatología', '722198005');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (64, 1, TRUE, 'Reproductive Medicine', 'Reproducción Humana', '722199002');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (65, 1, TRUE, 'Fertility Medicine', 'Fertilidad', '722200004');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (66, 1, TRUE, 'Andrology', 'Andrología', '722201000');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (67, 2, TRUE, 'Breast Surgery', 'Mastología', '722202007');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (68, 3, TRUE, 'Hepatology', 'Hepatología', '722203002');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (69, 1, TRUE, 'Clinical Nutrition', 'Nutrición Clínica', '722204008');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (70, 1, TRUE, 'Diabetology', 'Diabetología', '722205009');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (71, 1, TRUE, 'Integrative Medicine', 'Medicina Integrativa', '722206005');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (72, 1, TRUE, 'Aesthetic Medicine', 'Medicina Estética', '722207001');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (73, 8, TRUE, 'Acupuncture', 'Acupuntura', '722208006');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (74, 8, TRUE, 'Chiropractic', 'Quiropráctica', '722209003');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (75, 6, TRUE, 'Dentistry', 'Odontología', '722210008');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (76, 6, TRUE, 'Orthodontics', 'Ortodoncia', '722211007');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (77, 6, TRUE, 'Endodontics', 'Endodoncia', '722212000');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (78, 6, TRUE, 'Periodontics', 'Periodoncia', '722213005');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (79, 6, TRUE, 'Oral Implantology', 'Implantología Oral', '722214004');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (80, 2, TRUE, 'Oral Surgery', 'Cirugía Oral', '722215003');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (81, 6, TRUE, 'Pediatric Dentistry', 'Odontopediatría', '722216002');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (82, 6, TRUE, 'Prosthodontics', 'Prótesis Dental', '722217006');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (83, 5, TRUE, 'Physical Medicine', 'Medicina Física', '722218001');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (84, 7, TRUE, 'Physiotherapy', 'Fisioterapia', '722219009');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (85, 7, TRUE, 'Occupational Therapy', 'Terapia Ocupacional', '722220003');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (86, 7, TRUE, 'Speech Therapy', 'Fonoaudiología', '722221004');
INSERT INTO catalog.specialties (specialty_id, category_id, is_active, name_en, name_es, snomed_code)
OVERRIDING SYSTEM VALUE
VALUES (87, 4, TRUE, 'Clinical Psychology', 'Psicología Clínica', '722222006');


CREATE INDEX ix_appointment_clinical_details_tenant_id ON appointment.appointment_clinical_details (tenant_id);


CREATE INDEX ix_appointment_histories_tenant_id ON appointment.appointment_histories (tenant_id);


CREATE UNIQUE INDEX ix_appointments_appointment_number ON appointment.appointments (appointment_number);


CREATE UNIQUE INDEX ix_appointments_slot_id ON appointment.appointments (slot_id);


CREATE UNIQUE INDEX ix_countries_country_code ON geographic.countries (country_code);


CREATE INDEX ix_equipments_tenant_id ON facility.equipments (tenant_id);


CREATE INDEX ix_invoice_line_items_tenant_id ON billing.invoice_line_items (tenant_id);


CREATE INDEX ix_location_addresses_tenant_id ON organization.location_addresses (tenant_id);


CREATE INDEX ix_location_contacts_tenant_id ON organization.location_contacts (tenant_id);


CREATE INDEX ix_location_specialties_tenant_id ON organization.location_specialties (tenant_id);


CREATE UNIQUE INDEX ix_organizations_tax_id ON organization.organizations (tax_id);


CREATE INDEX ix_patient_addresses_tenant_id ON patient.patient_addresses (tenant_id);


CREATE INDEX ix_patient_consents_tenant_id ON patient.patient_consents (tenant_id);


CREATE INDEX ix_patient_contacts_tenant_id ON patient.patient_contacts (tenant_id);


CREATE INDEX ix_patient_insurances_tenant_id ON patient.patient_insurances (tenant_id);


CREATE INDEX ix_patient_relations_tenant_id ON patient.patient_relations (tenant_id);


CREATE INDEX ix_practitioner_contacts_tenant_id ON practitioner.practitioner_contacts (tenant_id);


CREATE INDEX ix_practitioner_locations_tenant_id ON practitioner.practitioner_locations (tenant_id);


CREATE INDEX ix_practitioner_specialties_tenant_id ON practitioner.practitioner_specialties (tenant_id);


CREATE INDEX ix_price_lists_tenant_id ON pricing.price_lists (tenant_id);


CREATE INDEX ix_refunds_tenant_id ON billing.refunds (tenant_id);


CREATE INDEX ix_rooms_tenant_id ON facility.rooms (tenant_id);


CREATE INDEX ix_schedule_exceptions_tenant_id ON scheduling.schedule_exceptions (tenant_id);


CREATE INDEX ix_service_prices_tenant_id ON pricing.service_prices (tenant_id);


CREATE INDEX ix_specialties_category_id ON catalog.specialties (category_id);


CREATE UNIQUE INDEX ix_specialties_snomed_code ON catalog.specialties (snomed_code);


CREATE UNIQUE INDEX ix_specialty_categories_code ON catalog.specialty_categories (code);


CREATE UNIQUE INDEX ix_telehealth_sessions_appointment_id ON appointment.telehealth_sessions (appointment_id);


CREATE INDEX ix_telehealth_sessions_tenant_id ON appointment.telehealth_sessions (tenant_id);


CREATE UNIQUE INDEX ix_users_email ON system.users (email);


CREATE INDEX ix_waitlists_tenant_id ON scheduling.waitlists (tenant_id);


SELECT setval(
    pg_get_serial_sequence('geographic.countries', 'country_id'),
    GREATEST(
        (SELECT MAX(country_id) FROM geographic.countries) + 1,
        nextval(pg_get_serial_sequence('geographic.countries', 'country_id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('catalog.document_types', 'type_id'),
    GREATEST(
        (SELECT MAX(type_id) FROM catalog.document_types) + 1,
        nextval(pg_get_serial_sequence('catalog.document_types', 'type_id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('catalog.specialty_categories', 'category_id'),
    GREATEST(
        (SELECT MAX(category_id) FROM catalog.specialty_categories) + 1,
        nextval(pg_get_serial_sequence('catalog.specialty_categories', 'category_id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('catalog.specialties', 'specialty_id'),
    GREATEST(
        (SELECT MAX(specialty_id) FROM catalog.specialties) + 1,
        nextval(pg_get_serial_sequence('catalog.specialties', 'specialty_id'))),
    false);


